version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ./app
    container_name: fastapi
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./app:/opt/app  # Mount the source code for live reload

  telegram-bot:
    build:
      context: ./bot  # Restrict build context to bot directory
      dockerfile: Dockerfile
    container_name: telegram-bot
    env_file: .env
    depends_on:
      - postgres
      - fastapi
    volumes:
      - ./bot:/opt/bot  # Bot source code
      - ./app:/opt/app  # App source code (shared utilities)
    command: ["python", "/opt/bot/main.py"]


