version: '3.1'

services:
  spark-master:
    build:
      context: ./spark_scripts
      dockerfile: Dockerfile.spark
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8081
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "8081:8081"
      - "7077:7077"
    volumes:
      - ./spark_scripts:/opt/airflow/spark_scripts
    networks:
      - airflow

  spark-worker:
    build:
      context: ./spark_scripts
      dockerfile: Dockerfile.spark
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./spark_scripts:/opt/airflow/spark_scripts
    networks:
      - airflow

networks:
  airflow: